// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


import './globals.css'; // Aapki global css
import Header from '../components/Header'; // Header Import kiya
import Footer from '../components/Footer'; // Footer Import kiya
import Script from 'next/script'; // Scripts ke liye
import type { Metadata } from 'next';
import { SITE_URL, SITE_NAME, SITE_TITLE, SITE_DESCRIPTION, SITE_KEYWORDS, CLINIC } from '../lib/site';

// SEO: Google search me title, description, keywords aur share preview yahi se banenge
export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: SITE_TITLE,
  description: SITE_DESCRIPTION,
  keywords: SITE_KEYWORDS,
  authors: [{ name: CLINIC.doctor }],
  alternates: { canonical: '/' },
  robots: { index: true, follow: true },
  // Google Search Console ownership verification (vercel.app wali property + neulifehomeo.in wali property)
  verification: {
    google: ['8NI5JQKo3iUvTdl4yS2ieMxpmZlQKptNwyvM-x7Z5W4', 'CTv1ZGIZWTr8tBRHnUD6buT4smGE9Q4MIo2xjzj5KZA'],
  },
  openGraph: {
    type: 'website',
    locale: 'en_IN',
    url: '/',
    siteName: SITE_NAME,
    title: SITE_TITLE,
    description: SITE_DESCRIPTION,
    images: [{ url: '/img/homeopathy-medicine.webp', width: 800, height: 907, alt: 'Homeopathic medicine at Neulife Homoeopathy Clinic, Jogeshwari West' }],
  },
  twitter: {
    card: 'summary_large_image',
    title: SITE_TITLE,
    description: SITE_DESCRIPTION,
    images: ['/img/homeopathy-medicine.webp'],
  },
  other: {
    'geo.region': 'IN-MH',
    'geo.placename': 'Jogeshwari West, Mumbai',
  },
};

// Google ko clinic ki details (address, phone, timing) structured form me batane ke liye
const clinicSchema = {
  '@context': 'https://schema.org',
  '@type': ['MedicalClinic', 'LocalBusiness'],
  name: CLINIC.name,
  alternateName: SITE_NAME,
  description: SITE_DESCRIPTION,
  url: SITE_URL,
  image: `${SITE_URL}/img/homeopathy-medicine.webp`,
  logo: `${SITE_URL}/images/homoepath-logo.png`,
  telephone: CLINIC.phone,
  email: CLINIC.email,
  medicalSpecialty: 'Homeopathic',
  priceRange: '₹₹',
  address: {
    '@type': 'PostalAddress',
    streetAddress: CLINIC.streetAddress,
    addressLocality: CLINIC.locality,
    addressRegion: CLINIC.region,
    postalCode: CLINIC.postalCode,
    addressCountry: CLINIC.country,
  },
  hasMap: `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(CLINIC.mapQuery)}`,
  areaServed: ['Jogeshwari West', 'Jogeshwari East', 'Andheri West', 'Goregaon', 'Mumbai'],
  openingHoursSpecification: [{
    '@type': 'OpeningHoursSpecification',
    dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    opens: CLINIC.openingHours.opens,
    closes: CLINIC.openingHours.closes,
  }],
  employee: {
    '@type': 'Physician',
    name: CLINIC.doctor,
    medicalSpecialty: 'Homeopathic',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en-IN">
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(clinicSchema) }}
        />
        {/* Saare CSS Links yahan aayenge */}
        <link rel="shortcut icon" type="image/x-icon" href="/images/favicon.png" />
        <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&display=swap" rel="stylesheet" />
        <link href="/css/bootstrap.min.css" rel="stylesheet" />
        <link href="/css/slicknav.min.css" rel="stylesheet" />
        <link href="/css/swiper-bundle.min.css" rel="stylesheet" />
        <link href="/css/all.min.css" rel="stylesheet" />
        <link href="/css/animate.css" rel="stylesheet" />
        <link href="/css/magnific-popup.css" rel="stylesheet" />
        <link href="/css/custom.css" rel="stylesheet" />
      </head>
      <body>
        
        {/* 1. Preloader (Optional, agar rakhna hai toh yahan rakho) */}
        
        {/* 2. Header Component */}
        <Header />

        {/* 3. Main Content (Ye page.tsx ka maal dikhayega) */}
        {children}

        {/* 4. Footer Component */}
        <Footer />

        {/* 5. Saare Scripts (jQuery, Slider etc.) */}
        <Script src="/js/jquery-3.7.1.min.js" strategy="beforeInteractive" />
        <Script src="/js/bootstrap.min.js" strategy="lazyOnload" />
        <Script src="/js/validator.min.js" strategy="lazyOnload" />
        <Script src="/js/jquery.slicknav.js" strategy="lazyOnload" />
        <Script src="/js/swiper-bundle.min.js" strategy="lazyOnload" />
        <Script src="/js/jquery.waypoints.min.js" strategy="lazyOnload" />
        <Script src="/js/jquery.counterup.min.js" strategy="lazyOnload" />
        <Script src="/js/isotope.min.js" strategy="lazyOnload" />
        <Script src="/js/jquery.magnific-popup.min.js" strategy="lazyOnload" />
        <Script src="/js/SmoothScroll.js" strategy="lazyOnload" />
        <Script src="/js/parallaxie.js" strategy="lazyOnload" />
        <Script src="/js/gsap.min.js" strategy="lazyOnload" />
      
        <Script src="/js/SplitText.js" strategy="lazyOnload" />
        <Script src="/js/ScrollTrigger.min.js" strategy="lazyOnload" />
        <Script src="/js/jquery.mb.YTPlayer.min.js" strategy="lazyOnload" />
        <Script src="/js/wow.min.js" strategy="lazyOnload" />
        <Script src="/js/function.js" strategy="lazyOnload" />

      </body>
    </html>
  );
}
